version: "3.9"

services:
  jira-servicedesk:
    image: atlassian/jira-servicemanagement:5.17.0   # Versión ITSM (Service Management)
    container_name: jira-servicedesk
    ports:
      - "8081:8080"
    environment:
      - ATL_JIRA_HOME=/var/atlassian/application-data/jira
    volumes:
      - jira_home:/var/atlassian/application-data/jira
    restart: unless-stopped

volumes:
  jira_home:
